const Dropdown16Data = [
  {
    text1: "α",
    text2:
      "Τάση δικτύου (VAC) <b>(Περιοχή τάσης λειτουργίας για τις οδηγίες) </b>",
    text3: "",
    values: [
      ["220V", "1BAT"],
      ["220V", "2BAT"],
      ["230V", "1BAT"],
      ["230V", "2BAT"],
      ["240V", "1BAT"],
      ["240V", "2BAT"],
      ["1BAT", ""],
      ["2BAT", ""],
    ],
  },
  {
    text1: "β",
    text2: "Ρεύμα δικτύου (mA AC) <b> (+5% του μέγιστου για τις οδηγίες)</b>",
    text3: "Συν.",
    text4: "Μη Συν.",
    input1: "",
    input2: "",
    input3: "",
    input4: "",
    input5: "",
    input6: "",
    input7: "",
    input8: "",
    input9: "",
    input10: "",
    input11: "",
    input12: "",
    input13: "",
    input14: "",
  },
  {
    text1: "γ",
    text2: "Πραγματική ισχύς (W) <b>(+5% της μέγιστης για τις οδηγίες) </b>",
    text3: "Συν.",
    text4: "Μη Συν.",
    input1: "",
    input2: "",
    input3: "",
    input4: "",
    input5: "",
    input6: "",
    input7: "",
    input8: "",
    input9: "",
    input10: "",
    input11: "",
    input12: "",
    input13: "",
    input14: "",
  },
  {
    text1: "δ",
    text2: "Ισχύς (VA) <b>(+5% της μέγιστης για τις οδηγίες) </b>",
    text3: "Συν.",
    text4: "Μη Συν.",
    input1: "",
    input2: "",
    input3: "",
    input4: "",
    input5: "",
    input6: "",
    input7: "",
    input8: "",
    input9: "",
    input10: "",
    input11: "",
    input12: "",
    input13: "",
    input14: "",
  },
  {
    text1: "ε",
    text2: "Power factor <b>(Ελάχιστο μετρούμενο για τις οδηγίες)</b>",
    text3: "Συν.",
    text4: "Μη Συν.",
    input1: "",
    input2: "",
    input3: "",
    input4: "",
    input5: "",
    input6: "",
    input7: "",
    input8: "",
    input9: "",
    input10: "",
    input11: "",
    input12: "",
    input13: "",
    input14: "",
  },
  {
    text1: "ζ",
    text2: "Συχνότητα δικτύου (Hz)",
    text3: "",
    text4: "50",
    text5: "50",
    text6: "50",
    text7: "50",
  },
];

export default Dropdown16Data;
